### ISSUE TITLE
Android support API >= 19

### ISSUE THREAD

**Issue by KORuL** [nats-io/java-nats-streaming#120] opened 2019-02-17 12:12 UTC
I'm trying to use the nats-streaming library, but it is written in Java 8, which does not allow using the Android API <26. This cuts off many android versions, everything below Android 8.0 - what to do in this situation if you need support for Android API> = 19

**Comment by sasbury** [comment] 2019-02-18 04:48
There is currently a pull request to alter the library to support < Java 8. https://github.com/nats-io/java-nats/pull/211 you can see from the discussion that it probably won't get merged into the master because it breaks existing apps, but it could form the basis of a streaming library with reduced requirements.

**Comment by sasbury** [comment] 2019-03-26 21:09
I am open to someone forking and porting on top of https://nats.io/download/kedzie/nats-android/ but I don't think we should pull the main library back for that.

**Closed by sasbury** 2019-03-26 21:09 UTC

**Comment by xianghu1314** [comment] 2020-12-04 09:37
@sasbury i use the nats streaming server and android app use this [nats-io/stan.java](https://github.com/nats-io/stan.java),but this is a error:
`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
        at io.nats.stan.ConnectionFactory.<init>(ConnectionFactory.java:22)
        at com.hycx.gogymcashier.model.utils.NatsStreamingUtils$1.run(NatsStreamingUtils.java:34)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.hycx.gogymcashier-2/base.apk"],nativeLibraryDirectories=[/data/app/com.hycx.gogymcashier-2/lib/arm, /data/app/com.hycx.gogymcashier-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at io.nats.stan.ConnectionFactory.<init>(ConnectionFactory.java:22) 
        at com.hycx.gogymcashier.model.utils.NatsStreamingUtils$1.run(NatsStreamingUtils.java:34) 
    	Suppressed: java.lang.ClassNotFoundException: java.time.Duration
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 3 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
    java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.hycx.gogymcashier-2/base.apk"],nativeLibraryDirectories=[/data/app/com.hycx.gogymcashier-2/lib/arm, /data/app/com.hycx.gogymcashier-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at io.nats.stan.ConnectionFactory.<init>(ConnectionFactory.java:22)
        at com.hycx.gogymcashier.model.utils.NatsStreamingUtils$1.run(NatsStreamingUtils.java:34)
    	Suppressed: java.lang.ClassNotFoundException: java.time.Duration
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 3 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`
this java.time.Duration is in java 8 what shou i do can solve this. my android device is android 6.thanks
